package org.picketbox.drools.authorization;

import java.security.Principal;
import org.picketbox.http.authorization.resource.WebResource;

dialect "mvel"

rule "Simple example rule that disables the section allocation"
dialect "java"
no-loop
 when
   $principal : Principal( name == "admin" ) // condition
   $resource : WebResource(getRequest().getRequestURI().contains("/admin/sectionAllocation"))
then
    modify ($resource){
       setAuthorized(false)
    };
end