package org.picketbox.drools.authorization;

import java.security.Principal;
import org.picketbox.http.authorization.resource.WebResource;

dialect "mvel"

rule "By default all resources are protected. This is a general rule to allows access to all resources"
dialect "java"
no-loop
 when
  $principal : Principal() // condition
  $resource : WebResource()
 then
    modify ($resource){
       setAuthorized(true)
    };
end